name: User
on:
  push:
    paths:
      - 'services/user-service/**'
      - '.github/workflows/**'
    branches:
      - master

  pull_request:
    paths:
      - 'services/user-service/**'
      - '.github/workflows/**'
    types:
      - opened
      - synchronize
      - reopened
  
jobs:
  sonarcloud: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        projectBaseDir: services/user-service
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: 06ff5d696333d2cb5c025f01f802679abf733d10
